#!/bin/bash
#
# This script was derived on 2021-01-09 from the post made by user "Vi." at
# https://stackoverflow.com/a/14329983/9116257, posted on 2013-01-15, edited on
# 2017-07-28, and is released under CC-BY-SA 3.0.  See LICENSE for more
# information.

git filter-branch -f  --index-filter \
    'git rm --force --cached --ignore-unmatch video/parasite-intro.avi' \
     -- --all
rm -Rf .git/refs/original && \
    git reflog expire --expire=now --all && \
    git gc --aggressive && \
    git prune

