#!/bin/bash

shopt -s expand_aliases
alias unpath="sed 's#^.*/##g'"

arg="${1}"

old_tag=$(
  git tag \
    | tail -n 1
)

if test '' == "${old_tag}"; then
  tag=0.0.0
else
  level=patch
  if test 'automatic' == "${arg}" -a -e ./api_tests; then
    if test -d .api_tests.previous.d; then
      for testfile in .api_tests.d/*; do
        while read line; do
          if echo "${line}" | grep -qv '^ *$'; then
            while read other_line; do
              if test "${line}" == "${other_line}"; then
                level=minor
              fi
            done < .api_tests.previous
          fi
        done < "${testfile}"
      done
      for testfile in .api_tests.previous.d/*; do
        while read line; do
          if echo "${line}" | grep -qv '^ *$'; then
            while read other_line; do
              if test "${line}" == "${other_line}"; then
                level=minor
              fi
            done < api_tests
          fi
        done < "${testfile}"
      done
      for testfile in .api_tests.previous.d/*; do
        testname="$(echo "${testfile}" | unpath)"
        if ! test -e .api_tests.d/"${testname}"; then
          level=major
        fi
      done
    fi
    cp api_tests .api_tests.previous
  fi

  case "${level}" in
    major)
      tag=$(
        echo "${old_tag}" \
          | sed 's/\./\n/g' \
          | { 
            readarray tag_parts
            let tag_parts[0]++
            tag_parts[1]=0
            tag_parts[2]=0
            for part in "${tag_parts[@]}"; do
              echo "${part}"
            done
          } \
          | while read l; do
            if echo "${l}" | grep -qE '[0-9]'; then
              echo -n $l'.'
            fi
          done \
          | sed 's/\.$//'
      )
      ;;
    minor)
      tag=$(
        echo "${old_tag}" \
          | sed 's/\./\n/g' \
          | { 
            readarray tag_parts
            let tag_parts[1]++
            tag_parts[2]=0
            for part in "${tag_parts[@]}"; do
              echo "${part}"
            done
          } \
          | while read l; do
            if echo "${l}" | grep -qE '[0-9]'; then
              echo -n $l'.'
            fi
          done \
          | sed 's/\.$//'
      )
      ;;
    patch)
      tag=$(
        echo "${old_tag}" \
          | sed 's/\./\n/g' \
          | { 
            readarray tag_parts
            let tag_parts[2]++
            for part in "${tag_parts[@]}"; do
              echo "${part}"
            done
          } \
          | while read l; do
            if echo "${l}" | grep -qE '[0-9]'; then
              echo -n $l'.'
            fi
          done \
          | sed 's/\.$//'
      )
      ;;
    *)
      echo "ERROR:  Unrecognized argument:  '${level}'"
      exit 1
      ;;
  esac
fi

echo "${level}" > /tmp/level.txt
git tag -a "${tag}" -m "Automatic ${level} increment."
