#!/bin/bash

PATH="$HOME/code/github/abugher/git-automation:${PATH}"

test_dir="/tmp/git-automation_tests"
test_repo="${test_dir}/repo"
master_repo="${test_dir}/master"
old_cwd="${PWD}"

test_count=0
failure_count=0
success_count=0

rm -rf "${test_dir}"
mkdir "${test_dir}"
mkdir "${master_repo}"
cd "${master_repo}"
git init --bare
git clone "${master_repo}" "${test_repo}"
cd "${test_repo}"
touch thing1
git add thing1
git commit
git push
touch thing2
cd "${old_cwd}"

for t in api_tests.d/*; do
  if test 'api_tests.d/*' == "${t}"; then
    continue
  fi
  echo "${t}"
  let test_count++
  sc=0
  fc=0
  tc=0
  while read command; do
    let tc++
    if eval "${command}" >/dev/null 2>&1; then
      #echo "Pass:  ${test_count}"
      let sc++
    else
      echo "Fail:  ${test_count}"
      let fc++
    fi
  done < "${t}"
  if test '0' == "${fc}"; then
    let success_count++
  else
    let failure_count++
  fi
  echo "Success:  ${sc}/${tc}"
  echo "Failures: ${fc}/${tc}"
done

echo "total"
echo "Success:  ${success_count}/${test_count}"
echo "Failures: ${failure_count}/${test_count}"
